/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaporRouteImport } from './routes/rapor'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSantriRouteImport } from './routes/_app.santri'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppNilaiIndexRouteImport } from './routes/_app.nilai.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppNilaiStudentIdRouteImport } from './routes/_app.nilai.$studentId'
import { Route as AppAdminTahunAjaranRouteImport } from './routes/_app.admin.tahun-ajaran'
import { Route as AppAdminPenggunaRouteImport } from './routes/_app.admin.pengguna'
import { Route as AppAdminMapelRouteImport } from './routes/_app.admin.mapel'
import { Route as AppAdminKelasRouteImport } from './routes/_app.admin.kelas'

const RaporRoute = RaporRouteImport.update({
  id: '/rapor',
  path: '/rapor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSantriRoute = AppSantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppNilaiIndexRoute = AppNilaiIndexRouteImport.update({
  id: '/nilai/',
  path: '/nilai/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppNilaiStudentIdRoute = AppNilaiStudentIdRouteImport.update({
  id: '/nilai/$studentId',
  path: '/nilai/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTahunAjaranRoute = AppAdminTahunAjaranRouteImport.update({
  id: '/tahun-ajaran',
  path: '/tahun-ajaran',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPenggunaRoute = AppAdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMapelRoute = AppAdminMapelRouteImport.update({
  id: '/mapel',
  path: '/mapel',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminKelasRoute = AppAdminKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rapor': typeof RaporRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/profil': typeof AppProfilRoute
  '/santri': typeof AppSantriRoute
  '/admin/kelas': typeof AppAdminKelasRoute
  '/admin/mapel': typeof AppAdminMapelRoute
  '/admin/pengguna': typeof AppAdminPenggunaRoute
  '/admin/tahun-ajaran': typeof AppAdminTahunAjaranRoute
  '/nilai/$studentId': typeof AppNilaiStudentIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/nilai/': typeof AppNilaiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rapor': typeof RaporRoute
  '/dashboard': typeof AppDashboardRoute
  '/profil': typeof AppProfilRoute
  '/santri': typeof AppSantriRoute
  '/admin/kelas': typeof AppAdminKelasRoute
  '/admin/mapel': typeof AppAdminMapelRoute
  '/admin/pengguna': typeof AppAdminPenggunaRoute
  '/admin/tahun-ajaran': typeof AppAdminTahunAjaranRoute
  '/nilai/$studentId': typeof AppNilaiStudentIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/nilai': typeof AppNilaiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/rapor': typeof RaporRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/santri': typeof AppSantriRoute
  '/_app/admin/kelas': typeof AppAdminKelasRoute
  '/_app/admin/mapel': typeof AppAdminMapelRoute
  '/_app/admin/pengguna': typeof AppAdminPenggunaRoute
  '/_app/admin/tahun-ajaran': typeof AppAdminTahunAjaranRoute
  '/_app/nilai/$studentId': typeof AppNilaiStudentIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/nilai/': typeof AppNilaiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rapor'
    | '/admin'
    | '/dashboard'
    | '/profil'
    | '/santri'
    | '/admin/kelas'
    | '/admin/mapel'
    | '/admin/pengguna'
    | '/admin/tahun-ajaran'
    | '/nilai/$studentId'
    | '/admin/'
    | '/nilai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rapor'
    | '/dashboard'
    | '/profil'
    | '/santri'
    | '/admin/kelas'
    | '/admin/mapel'
    | '/admin/pengguna'
    | '/admin/tahun-ajaran'
    | '/nilai/$studentId'
    | '/admin'
    | '/nilai'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/rapor'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/profil'
    | '/_app/santri'
    | '/_app/admin/kelas'
    | '/_app/admin/mapel'
    | '/_app/admin/pengguna'
    | '/_app/admin/tahun-ajaran'
    | '/_app/nilai/$studentId'
    | '/_app/admin/'
    | '/_app/nilai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RaporRoute: typeof RaporRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rapor': {
      id: '/rapor'
      path: '/rapor'
      fullPath: '/rapor'
      preLoaderRoute: typeof RaporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/santri': {
      id: '/_app/santri'
      path: '/santri'
      fullPath: '/santri'
      preLoaderRoute: typeof AppSantriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nilai/': {
      id: '/_app/nilai/'
      path: '/nilai'
      fullPath: '/nilai/'
      preLoaderRoute: typeof AppNilaiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/nilai/$studentId': {
      id: '/_app/nilai/$studentId'
      path: '/nilai/$studentId'
      fullPath: '/nilai/$studentId'
      preLoaderRoute: typeof AppNilaiStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tahun-ajaran': {
      id: '/_app/admin/tahun-ajaran'
      path: '/tahun-ajaran'
      fullPath: '/admin/tahun-ajaran'
      preLoaderRoute: typeof AppAdminTahunAjaranRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/pengguna': {
      id: '/_app/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AppAdminPenggunaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/mapel': {
      id: '/_app/admin/mapel'
      path: '/mapel'
      fullPath: '/admin/mapel'
      preLoaderRoute: typeof AppAdminMapelRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/kelas': {
      id: '/_app/admin/kelas'
      path: '/kelas'
      fullPath: '/admin/kelas'
      preLoaderRoute: typeof AppAdminKelasRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminKelasRoute: typeof AppAdminKelasRoute
  AppAdminMapelRoute: typeof AppAdminMapelRoute
  AppAdminPenggunaRoute: typeof AppAdminPenggunaRoute
  AppAdminTahunAjaranRoute: typeof AppAdminTahunAjaranRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminKelasRoute: AppAdminKelasRoute,
  AppAdminMapelRoute: AppAdminMapelRoute,
  AppAdminPenggunaRoute: AppAdminPenggunaRoute,
  AppAdminTahunAjaranRoute: AppAdminTahunAjaranRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfilRoute: typeof AppProfilRoute
  AppSantriRoute: typeof AppSantriRoute
  AppNilaiStudentIdRoute: typeof AppNilaiStudentIdRoute
  AppNilaiIndexRoute: typeof AppNilaiIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppProfilRoute: AppProfilRoute,
  AppSantriRoute: AppSantriRoute,
  AppNilaiStudentIdRoute: AppNilaiStudentIdRoute,
  AppNilaiIndexRoute: AppNilaiIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RaporRoute: RaporRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
